image: alphine:3.7

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir ~/.ssh
  - ssh-keyscan -t rsa devsb01 >> ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - mkdir -p /go/src/gitlab.com/dockerdeploytest /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/dockerdeploytest
  - ls $CI_PROJECT_DIR
  - ln -s /go/src/gitlab.com/dockerdeploytest /go/src/_/builds/dockerdeploytest
  - cd src && make dep

stages:
  - test
  - build

test:
  stage: test
  image: golang:1.9
  script:
    - go test ./...

build:
  image: golang:1.9
  stage: build
  script:
    - go build