image: alphine:3.7

before_script:
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
  - mkdir ~/.ssh
  - ssh-keyscan -t rsa devsb01 >> ~/.ssh/known_hosts
  - git remote set-url origin git@gitlab.com/ghanesh.balaji1995/DockerDeployTest.git
  - mkdir -p /go/src/gitlab.com/dockerdeploytest /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/dockerdeploytest
  - ls $CI_PROJECT_DIR
  - ln -s /go/src/gitlab.com/dockerdeploytest /go/src/_/builds/dockerdeploytest
  - cd src && make dep

stages:
  - test
  - build

test:
  stage: test
  image: golang:1.9
  script:
    - go test ./...

build:
  image: golang:1.9
  stage: build
  script:
    - go build