image: golang:1.9

before_script:
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - mkdir -p /go/src/gitlab.com/dockerdeploytest /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/dockerdeploytest/src
  - ls $CI_PROJECT_DIR
  - ln -s /go/src/gitlab.com/dockerdeploytest /go/src/_/builds/dockerdeploytest
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - cd src && make dep

stages:
  - test
  - build

test:
  stage: test
  image: golang:1.9
  script:
    - go test ./...

build:
  image: golang:1.9
  stage: build
  script:
    - go build