image: alphine:3.7

variables:
  PACKAGE_PATH: /go/src/gitlab.com/ghanesh.balaji1995/dockerdeploytest

before_script:
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir ~/.ssh
  - ssh-keyscan -t rsa devsb01 >> ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - git remote set-url origin git@gitlab.com/ghanesh.balaji1995/DockerDeployTest.git

stages:
  - deploy
  - heroku

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker pull shreegb/docker_deploy_test:latest
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker tag shreegb/docker_deploy_test registry.heroku.com/sleepy-chamber-71815:latest
    - docker push registry.heroku.com/sleepy-chamber-71815:latest

deploy_to_heroku:
  image: node:latest
  stage: heroku
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - heroku container:login
    - npm install -g heroku
    - heroku container:release web --app sleepy-chamber-71815